google.drive.credentials-json=${GOOGLE_DRIVE_CREDENTIALS_JSON:}
google.drive.folder-id=${GOOGLE_DRIVE_FOLDER_ID:}
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB
